# Generated by Django 5.2.4 on 2026-07-18 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freestyler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('start_datetime_utc', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['start_datetime_utc'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.IntegerField(blank=True, null=True)),
                ('score_2', models.IntegerField(blank=True, null=True)),
                ('is_exhibition', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('finished', 'Finalizada')], max_length=20)),
                ('mc_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_mc1', to='core.freestyler')),
                ('mc_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_mc2', to='core.freestyler')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to='core.freestyler')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='core.matchday')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.competition')),
            ],
        ),
        migrations.AddField(
            model_name='matchday',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchdays', to='core.season'),
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('pts', models.IntegerField(default=0)),
                ('ptb', models.FloatField(default=0.0)),
                ('battles_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('wins_replica', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('losses_replica', models.IntegerField(default=0)),
                ('mvp', models.IntegerField(default=0)),
                ('freestyler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.freestyler')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.season')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('season', 'freestyler')},
            },
        ),
    ]
