# Generated by Django 5.2.4 on 2026-07-18 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.battle')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='core.matchday')),
            ],
        ),
    ]
