# Generated by Django 5.2.4 on 2026-07-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tournamentbracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='has_replica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battle',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='votes_mc_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='votes_mc_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='votes_replica',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
